spring:
  datasource:
    url: jdbc:mysql://sql6.freesqldatabase.com/sql6641956
    username: sql6641956
    password: kKvbDFnCwt
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true

